import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Check, ChevronRight, X } from 'lucide-react-native';
import type { Reminder } from '../lib/types';
import { deleteReminder, setReminderStatus } from '../lib/reminders';
import { formatReminderDueAt } from '../lib/format';
import { useTheme, space, radius, fontSize, type Theme } from '../lib/theme';

// Mirrors the PWA's EventReminderGroup exactly (read off page.tsx +
// event-reminder-group.tsx source, only used in the "N reminder selesai"
// collapsed section of Semua's Reminder tab): a chain of Event Mode
// reminders (H-7/H-3/H-1/H0, generated by a DB trigger off a checklist's
// target_date or a trip's start_date) rendered as one card with a
// title/icon header instead of 4 scattered rows. Each stage is a compact
// row — checkbox + label + time + delete — not the full expand-to-detail
// ReminderRow gets, matching the PWA's own StageRow (deliberately terser
// than a standalone reminder since it's already nested one level deep).
export default function EventReminderGroup({
  title,
  icon,
  reminders,
  onChanged,
}: {
  title: string;
  icon: string;
  reminders: Reminder[];
  onChanged: () => void;
}) {
  const theme = useTheme();
  const styles = makeStyles(theme);
  const sorted = [...reminders].sort((a, b) => new Date(a.due_at).getTime() - new Date(b.due_at).getTime());

  return (
    <View style={styles.card}>
      <View style={styles.header}>
        <Text style={styles.headerIcon}>{icon}</Text>
        <Text style={styles.headerTitle} numberOfLines={1}>
          {title}
        </Text>
        <ChevronRight size={14} color={theme.color.chevron} />
      </View>
      <View style={styles.stageList}>
        {sorted.map((r) => (
          <StageRow key={r.id} reminder={r} onChanged={onChanged} />
        ))}
      </View>
    </View>
  );
}

function StageRow({ reminder, onChanged }: { reminder: Reminder; onChanged: () => void }) {
  const theme = useTheme();
  const styles = makeStyles(theme);
  const [confirming, setConfirming] = useState(false);
  const [pending, setPending] = useState(false);
  const done = reminder.status === 'done';

  async function toggle() {
    setPending(true);
    try {
      await setReminderStatus(reminder.id, done ? 'pending' : 'done');
      onChanged();
    } catch (err) {
      Alert.alert('Gagal', err instanceof Error ? err.message : 'Gagal mengubah status.');
    } finally {
      setPending(false);
    }
  }

  async function remove() {
    setPending(true);
    try {
      await deleteReminder(reminder.id);
      onChanged();
    } catch (err) {
      Alert.alert('Gagal', err instanceof Error ? err.message : 'Gagal menghapus reminder.');
    } finally {
      setPending(false);
    }
  }

  return (
    <View style={styles.stageRow}>
      <Pressable
        style={[styles.stageCheckbox, done && styles.stageCheckboxChecked]}
        onPress={toggle}
        disabled={pending}
        hitSlop={8}
        accessibilityRole="checkbox"
        accessibilityState={{ checked: done }}
      >
        {done && <Check size={11} color={theme.color.onPrimary} strokeWidth={3} />}
      </Pressable>
      <Text style={[styles.stageLabel, done && styles.stageLabelDone]} numberOfLines={1}>
        {reminder.event_stage}
      </Text>
      <Text style={styles.stageTime}>{formatReminderDueAt(reminder.due_at)}</Text>
      {confirming ? (
        <View style={styles.confirmRow}>
          <Pressable onPress={remove} disabled={pending} hitSlop={6}>
            <Text style={styles.confirmYes}>{pending ? '…' : 'Ya'}</Text>
          </Pressable>
          <Pressable onPress={() => setConfirming(false)} disabled={pending} hitSlop={6}>
            <Text style={styles.confirmNo}>Batal</Text>
          </Pressable>
        </View>
      ) : (
        <Pressable onPress={() => setConfirming(true)} hitSlop={8} accessibilityLabel="Hapus reminder">
          <X size={13} color={theme.color.chevron} />
        </Pressable>
      )}
    </View>
  );
}

function makeStyles(theme: Theme) {
  return StyleSheet.create({
    card: {
      borderRadius: radius.card,
      borderWidth: 1,
      borderColor: theme.color.border,
      backgroundColor: theme.color.surface,
      paddingHorizontal: space.sm + 2,
      paddingVertical: space.sm + 2,
      marginBottom: space.sm,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.xs + 2,
      marginBottom: space.xs + 2,
    },
    headerIcon: {
      fontSize: fontSize.sm,
    },
    headerTitle: {
      flex: 1,
      fontSize: fontSize.sm,
      fontWeight: '600',
      color: theme.color.text,
    },
    stageList: {
      gap: 2,
    },
    stageRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.xs + 2,
      paddingVertical: space.xs + 2,
      borderTopWidth: 1,
      borderTopColor: theme.color.border,
    },
    stageCheckbox: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: theme.color.checkboxBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stageCheckboxChecked: {
      backgroundColor: theme.color.primary,
      borderColor: theme.color.primary,
    },
    stageLabel: {
      flex: 1,
      fontSize: fontSize.xs,
      fontWeight: '500',
      color: theme.color.text,
    },
    stageLabelDone: {
      textDecorationLine: 'line-through',
      color: theme.color.textMuted,
    },
    stageTime: {
      fontSize: fontSize.tiny,
      color: theme.color.textMuted,
    },
    confirmRow: {
      flexDirection: 'row',
      gap: space.xs + 2,
    },
    confirmYes: {
      fontSize: fontSize.tiny,
      fontWeight: '600',
      color: theme.color.destructive,
    },
    confirmNo: {
      fontSize: fontSize.tiny,
      color: theme.color.textMuted,
    },
  });
}
